### ISSUE TITLE
Prop possession Punch-o-meter strength based on karma

### ISSUE THREAD

**Issue by matekdev** [CigarLounge/sbox-TTT#186]
We should let people have more punches / recharge faster if they have higher karma.

**Comment by mzegar** [comment]
clamp(ceil(karma / 2), -6, 16) as a base formula, play around with it.

**Comment by matekdev** [comment]
https://github.com/CigarLounge/sbox-TTT/commit/03113de340950d1cedc345ca84d1b8ed73d79eaa
