### ISSUE TITLE
Prop possession left and right movement is terrible

### ISSUE THREAD

**Issue by matekdev** [CigarLounge/sbox-TTT#187]
Try possessing a prop and use `A`/`D` to move, it doesn't really move much. We should make it more effective.

**Comment by mzegar** [comment]
```
prop movement feels kind of rigid and not what you would expect. Should be able to get air with them easily.
```

Maybe we can decreas the friction when handling a prop? Play around and see if we can fix this as well.

**Comment by matekdev** [comment]
https://github.com/CigarLounge/sbox-TTT/commit/3983c1287fb1297d7836c10d88e416eeeaef8474 fixed
