### ISSUE TITLE
Traitors should always win if all innos die on round end

### ISSUE THREAD

**Issue by KingOfTheFBI** [CigarLounge/sbox-TTT#190]
Not sure how it is handled in old TTT code wise. But basically it would make traitors win every round where everyone left dies at once. (ex jihad, c4, explosive barrel)

This makes sense because the objective of the innos is to kill all traitors and survive. Whereas the traitor objective is to just kill all the innos at any cost.

**Comment by the-remeko** [comment]
Checking for a winner every 1-2 seconds (like gmod TTT) instead of after every kill might be the cleanest option to fix this, unless there's a way to check at the end of every tick. We might be able to check at the end of Game.Simulate(), but there are Event.Tick.Server functions that can cause damage (C4), and I don't know if those are called before/after Simulate(), or even asynchronously.

**Comment by mzegar** [comment]
I don't think this needs to be handled. Whoever is the last survivor should be the winner. @kolexxx

**Comment by the-remeko** [comment]
> I don't think this needs to be handled. Whoever is the last survivor should be the winner. @kolexxx what do you think

The game checks for a winner at the end of TakeDamage(). If an explosion kills all remaining players, the winner may be random, unlike in gmod TTT where the game makes Ts win if everyone dies at the same time.

**Comment by KingOfTheFBI** [comment]
> > I don't think this needs to be handled. Whoever is the last survivor should be the winner. @kolexxx what do you think
> 
> The game checks for a winner at the end of TakeDamage(). If an explosion kills all remaining players, the winner may be random, unlike in gmod TTT where the game makes Ts win if everyone dies at the same time.

Yeah, that's my point.

**Comment by mzegar** [comment]
> > I don't think this needs to be handled. Whoever is the last survivor should be the winner. @kolexxx what do you think
> 
> The game checks for a winner at the end of TakeDamage(). If an explosion kills all remaining players, the winner may be random, unlike in gmod TTT where the game makes Ts win if everyone dies at the same time.

When a player dies, it checks to see if the round is over. Wouldn't the first death be the trigger that checks this?

**Comment by the-remeko** [comment]
> > > I don't think this needs to be handled. Whoever is the last survivor should be the winner. @kolexxx what do you think
> > 
> > 
> > The game checks for a winner at the end of TakeDamage(). If an explosion kills all remaining players, the winner may be random, unlike in gmod TTT where the game makes Ts win if everyone dies at the same time.
> 
> When a player dies, it checks to see if the round is over. Wouldn't the first death be the trigger that checks this?

Yes. When a C4 explodes, it loops through the nearby players and damages them in series. If all living players would be killed by the C4, then whichever team is completely killed first in the loop loses the round.

You _could_ just order the players in the loop by their team, but there's also the problem of explosive barrels...

**Comment by mzegar** [comment]
> > > > I don't think this needs to be handled. Whoever is the last survivor should be the winner. @kolexxx what do you think
> > > 
> > > 
> > > The game checks for a winner at the end of TakeDamage(). If an explosion kills all remaining players, the winner may be random, unlike in gmod TTT where the game makes Ts win if everyone dies at the same time.
> > 
> > 
> > When a player dies, it checks to see if the round is over. Wouldn't the first death be the trigger that checks this?
> 
> Yes. When a C4 explodes, it loops through the nearby players and damages them in series. If all living players would be killed by the C4, then whichever team is completely killed first in the loop loses the round.
> 
> You _could_ just order the players in the loop by their team, but there's also the problem of explosive barrels...

Right, if we use `Client.All` then it could apply the damage in the wrong order (i.e someone on the outside gets killed first).

**Comment by the-remeko** [comment]
Instead of checking for victory after every kill, we could check for victory by elimination using Event.Tick.Server. According to my testing, all players are registered dead the tick after they are killed at the same time by an explosion.

We could even derive an event from Event.Tick.ServerAttribute with a lower priority to guarantee that the check happens after any Event.Tick.Server events that may kill multiple people at the same time:

	public class TickEndAttribute : Event.Tick.ServerAttribute
	{
		public TickEndAttribute() : base()
		{
			Priority = 1; // higher Priority = lower priority
		}
	}

**Comment by matekdev** [comment]
https://github.com/CigarLounge/sbox-TTT/commit/e5243fa514c283ab77df7f823d518e3b8cb331c7

Changed to be like vanilla
