### ISSUE TITLE
A More Perfect License

### ISSUE THREAD

**Issue by ndo360** [CigarLounge/sbox-TTT#207]
Greetings!

As discussed on the server the CC-BY-NC-SA 4.0 license is not advised to be used for programming code. As such I think we could follow from example to form a better license that makes things more clear. Below I posted two examples:

Valve's SDK License:
https://github.com/ValveSoftware/source-sdk-2013/blob/master/LICENSE

Delta Green's License
https://www.delta-green.com/field-reports-and-fan-creations/

The reason I post both of them is for reference in how both handle derivative content. In the next post I'll post a license I cobbled together that could be edited as desired and go from there. Hopefully we can design "a more perfect license" haha... 😅

**Comment by ndo360** [comment]
https://github.com/Facepunch/Legal -- Also adding this as a good resource to look over.

**Comment by mzegar** [comment]
https://github.com/sbox-TTT/TTT/pull/210

**Comment by matekdev** [comment]
Thanks for leading this @ndo360
