### ISSUE TITLE
Hands do not show during preparing

### ISSUE THREAD

**Issue by matekdev** [CigarLounge/sbox-TTT#222]
Since they are considered not `Spawnable` and you don't have a role, our UI does not show the hands.

**Comment by Ephememory** [comment]
![image](https://user-images.githubusercontent.com/66768086/210833569-bec60352-5197-48fc-9752-968d6f30b5c4.png)
I believe this is fixed. I can't reproduce it. I can't imagine it somehow fixed itself but 🤷

**Comment by matekdev** [comment]
Yeah I forgot to add a `IsSpawnable` check, but anyways, I think it's fine to keep it as is.
