### ISSUE TITLE
Two hit knife

### ISSUE THREAD

**Issue by matekdev** [CigarLounge/sbox-TTT#223]
The knife should be two attacks from the front, or one from the back.

**Comment by Ephememory** [comment]
How do we want to handle the knife being consumed? If we change to two attacks from the front then there is a case where one could attack multiple people multiple times without destroying the knife.

I haven't put much thought into it but I see two options:

A.) The knife only gets destroyed when the attack resulted in a kill, meaning you can slash multiple people in the front if their health values are high enough.

B.) Increment on every attack and the knife will be destroyed on the second attack regardless of if the attack resulted in a kill. As for the backstabs, they obviously result in a kill and will destroy the knife in the single attack.

**Comment by matekdev** [comment]
However it works in vanilla, I'm assuming it works like A) in vanilla.

**Comment by Ephememory** [comment]
> However it works in vanilla, I'm assuming it works like A) in vanilla.

Alright. I'll have to boot up Garry's Mod and actually check since I'm not seeing anything about additional damage from backstabs on the wikis.

**Comment by Ephememory** [comment]
@matekdev PR ready for review.
