### ISSUE TITLE
Bullet penetration

### ISSUE THREAD

**Issue by matekdev** [CigarLounge/sbox-TTT#240]
We need some form of bullet penetration, it doesn't make sense that bullets don't go through glass. It doesn't have to be strong, maybe just pass through fairly thin materials.

**Comment by KingOfTheFBI** [comment]
Sounds like a bad idea for opaque things to be shot through. The way TTT has always worked is you can see enemies when they shoot you always if you are looking at them. Will also lead to things like RDM in reactionary fire etc.

Transparent materials and glass is fine though.

**Comment by matekdev** [comment]
I'll split em up for now
