### ISSUE TITLE
General Bullet penetration

### ISSUE THREAD

**Issue by matekdev** [CigarLounge/sbox-TTT#242]
General bullet penetration, we should determine a width such that it doesn't make every single wall wallbangable. Is this even possible? Not sure, investigate.

**Comment by kythre** [comment]
what i found to work is casting a thin-radius (0.2 units) ray about 2 units (normal ray radius?) offset from the endposition of the ray that hit the wall, the thin ray would then hit the opposite end of the wall from the inside and i would just check if the length of that ray is less than 25 units to determine if the bullet gets "absorbed" or if to cast another ray beyond the wall for penetration

**Comment by kythre** [comment]
some other things ill throw out there: perhaps bullet penetration through players and also a TraceBullet rework to also return if its a penetration shot for kill logging and damage reduction
