### ISSUE TITLE
Punch-o-Meter remains on screen post round end.

### ISSUE THREAD

**Issue by LubricantJam** [CigarLounge/sbox-TTT#245]
![Image](https://i.imgur.com/gq0U74g.jpeg)

**Comment by matekdev** [comment]
@kolexxx do you think this is another s&box networking thing? We make sure to delete the meter when the component is de-activated.

**Comment by matekdev** [comment]
Thanks for the bug report, if you run into it again let me know. I tested this out and it seems to be in order.
