### ISSUE TITLE
It's incredibly hard to see where you have been shot from.

### ISSUE THREAD

**Issue by GlivGluv** [CigarLounge/sbox-TTT#247]
The original game had tracer rounds for all weapons and a larger indicator as to where you took damage from, as well as the fact you took damage at all. (Big red screen)

I think this needs it too. The bullets are basically invisible.

**Comment by matekdev** [comment]
Yeah I agree, we should see what we can do to improve this.

**Comment by matekdev** [comment]
@GlivGluv I modified some stuff, if this still sucks reopen another ticket.
