### ISSUE TITLE
TTT walk keybinding bound to s&box run keybinding instead of walk

### ISSUE THREAD

**Issue by brewfest** [CigarLounge/sbox-TTT#252]
title

**Comment by matekdev** [comment]
Shift is pretty common to walk in most games, we'll keep it as shift for now. s&box I think is changin the way the keybinding system works.

**Comment by brewfest** [comment]
that makes no sense, the user can bind it to whatever they want but as it is now they have to use the s&box run binding to affect the walk binding in ttt. just change it to use the s&box walk binding and then people can easily change the binding if they so wish without being confused
