### ISSUE TITLE
Pickup/Push Doesn't Match gmod TTT

### ISSUE THREAD

**Issue by brewfest** [CigarLounge/sbox-TTT#257]
As it is now in s&box TTT you only have the options to pickup or push physics objects given they are below certain weight and dimension requirements. In gmod TTT if an object's weight was to high to pickup you would instead pull the object towards you with the speed matching that of the push speed at any given weight. The keybindings in s&box are also reversed from what it is in gmod, which was basically the same as the gravity gun.

For logical, gameplay, and traditional reasons I think pickup/push should function as it did in gmod. Weight and speed limits don't need to match exactly, but the system as a whole should be pretty much the same.

**Comment by matekdev** [comment]
Magneto.
