### ISSUE TITLE
Update C# summaries with extra information

### ISSUE THREAD

**Issue by matekdev** [CigarLounge/sbox-TTT#269]
We should use `<param>` during our summaries https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#param

We should also potentially use `<returns>` https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#returns

Update the current summaries we have with these tags.

**Comment by Flexusaurs** [comment]
started doing some work on the docs today, can i push the stuff I've already started working on? it's not much but still added some params to various blocks

**Comment by Flexusaurs** [comment]
can you open a new branch for documentation updates so I can do a PR? or should i just commit stuff directly to main?

**Comment by matekdev** [comment]
You can push all the changes to your own branch, then open a PR for that new branch you opened.
