### ISSUE TITLE
Convert to using PlayerStatus?

### ISSUE THREAD

**Issue by matekdev** [CigarLounge/sbox-TTT#278]
It seems really odd that in one specific case we are checking the player status whereas everywhere else we use `IsAlive()`, can we convert to one or the other in all cases?

https://github.com/CigarLounge/sbox-TTT/blob/main/code/Player/Cameras/FirstPersonCamera.cs#L15

**Comment by kolexxx** [comment]
I have a feeling `LifeState` will be removed. Besides `PlayerStatus` can completely replace it. I will have a pr for this.

**Comment by matekdev** [comment]
ya either or is fine, when you have time, otherwise what we have is good.

**Comment by matekdev** [comment]
https://github.com/CigarLounge/sbox-TTT/pull/282
