### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by matekdev** [CigarLounge/sbox-TTT#286]
Lets add localization by using the s&box system
https://wiki.facepunch.com/sbox/localization

**Comment by Ephememory** [comment]
I call dibs on pirate and lolcat

**Comment by matekdev** [comment]
How do we want to handle the naming for the localization strings?

```
{
    "TabMenu.Menu": "Menu"
}
```
prefix with the UI element it references?

```
{
    "Menu": "Menu"
}
```
Just a string that matches?

```
{
    "Game.Menu": "Menu"
}
```
Maybe some other prefix?

**Comment by Ephememory** [comment]
Definitely prefixing it with the UI element it's apart of. Other than that I'm not very concerned.
