### ISSUE TITLE
Traitors lose if everyone dies.

### ISSUE THREAD

**Issue by DeeMoney7** [CigarLounge/sbox-TTT#290]
https://user-images.githubusercontent.com/80512693/211178767-f553043b-b511-450d-9019-35ab3649295b.mp4

C4 blew me and the only inno bot up. Traitors lose. Innos win. Believe this is backwards.

**Comment by matekdev** [comment]
https://github.com/CigarLounge/sbox-TTT/commit/e5243fa514c283ab77df7f823d518e3b8cb331c7
