### ISSUE TITLE
Timer to force map rotation

### ISSUE THREAD

**Issue by matekdev** [CigarLounge/sbox-TTT#299]
Right now, the map only changes once `ttt_round_limit` number of rounds have been played. However, we should also have another timer that will force map selection if it runs out. As the rounds could last very long if the player count is large. Basically, if either the timer runs out or the number of rounds have been played, go to map selection.

This timer should be on the scoreboard next to the round limit, should have a convar which can be changed, and should take the default value in vanilla.

**Comment by Ephememory** [comment]
I want this if no one else wants to do it.

**Comment by matekdev** [comment]
ASSIGNED

**Comment by Ephememory** [comment]
Should we only check that this timer has passed the limit in `InProgress` state? Currently I'm doing it in `BaseState`.
