### ISSUE TITLE
Add weapon spawn selector

### ISSUE THREAD

**Issue by SemberStratos** [CigarLounge/sbox-TTT#302]
As different weapon bases and add-ons become available, users may want to select which weapons are spawned each round.

For example, in gmod, when my friends and I had added the TFA weapon base to our server, CSS weapons would still spawn when we only wanted weapons using the TFA base to spawn. To fix this, we had to manually change stuff in the configuration files on the server when it could've been a toggle switch in a settings menu.

**Comment by matekdev** [comment]
Depending on how s&box addons behave, I don't think we will need to change anything for this. Too early to tell.

**Comment by matekdev** [comment]
I'm going to close this issue for now, if this ends up being a problem in the long run please feel free to open it up again.

The idea should be that people can simply delete the original weapon asset files to stop them from spawning. But, we'll see how this behaves once FacePunch has iterated on the addon support for the game.
