### ISSUE TITLE
Toggle Sprint in Settings

### ISSUE THREAD

**Issue by SemberStratos** [CigarLounge/sbox-TTT#303]
In the settings menu, having a Sprint w/stamina option to toggle before starting the game would be excellent for those who prefer TTT with sprinting.

Additionally, a double-jump feature would be nice, though I see this being more of an add-on, as fewer people probably would use double-jumping in their games.

**Comment by matekdev** [comment]
We don't have any plans on adding settings to toggle on features like this. Sprinting can be simply can addon.

The only settings/convars will be things like knife backstabs. 

If you want me to expand more about this we can chat on Discord.

**Comment by SemberStratos** [comment]
Sure thing! I might have some time this weekend; I could develop it as an addon myself to become familiar with s&box.

Do you have any tips/guides you recommend?

**Comment by matekdev** [comment]
> Sure thing! I might have some time this weekend; I could develop it as an addon myself to become familiar with s&box.
> 
> Do you have any tips/guides you recommend?

I haven't worked with add-ons yet. But, you'd make an addon project for TTT. You'd change the walk controller to sprint instead of walk when pressing shift. Then, if you wanted UI you could also add that as well. I'd suggest checking out the wiki.

**Comment by SemberStratos** [comment]
> > Sure thing! I might have some time this weekend; I could develop it as an addon myself to become familiar with s&box.
> > 
> > Do you have any tips/guides you recommend?
> 
> I haven't worked with add-ons yet. But, you'd make an addon project for TTT. You'd change the walk controller to sprint instead of walk when pressing shift. Then, if you wanted UI you could also add that as well. I'd suggest checking out the wiki. 

Thanks for the info! I will see what I can cook up
