### ISSUE TITLE
Add Magneto Stick

### ISSUE THREAD

**Issue by matekdev** [CigarLounge/sbox-TTT#308]
Let's add the magneto stick, make sure prop killing doesn't happen.

**Comment by brewfest** [comment]
I know the damage players can take from props is broken in s&box, bure surely intentionally completely removing such a core component from source games and TTT is a mistake? While the physics is bad it makes sense, but there should be plans to allow for prop killing in the future

**Comment by Ephememory** [comment]
What will we use for models and animations?

**Comment by brewfest** [comment]
If it works the same or almost the same as magneto stick in Gmod should probably be just that. There are like 100 remodols of it for various projects so I'm sure we could find one that looks better than stock hl2 that we could get permission to use. Would be interesting to use the gravity gloves from Alex though.

**Comment by Ephememory** [comment]
> If it works the same or almost the same as magneto stick in Gmod should probably be just that. There are like 100 remodols of it for various projects so I'm sure we could find one that looks better than stock hl2 that we could get permission to use. Would be interesting to use the gravity gloves from Alex though "no hla porting allowed"

I see. There are a few reasons I think we wouldn't want to use the gravity gloves from HL:A regardless, one being copyright infringement on Valve.  I just remember the pain points from the last discussion of the magneto stick relating to the models and prop killing, so let's get that all decided if we're going to add it.
