### ISSUE TITLE
Bullets need tracer rounds

### ISSUE THREAD

**Issue by GlivGluv** [CigarLounge/sbox-TTT#321]
Bullets in vanilla TTT were visible while in the air, allowing other people to see where they came from even if it was for a brief moment. Currently they are invisible.

I don't think this effect is applied to silenced weapons, however. This will have to be checked.

**Comment by Ephememory** [comment]
https://github.com/CigarLounge/sbox-TTT/issues/247

**Comment by matekdev** [comment]
😱

**Comment by matekdev** [comment]
https://streamable.com/ebv1fa

We need to modify the current tracer particles to look a bit better. We also need to update all game resources to actually use the tracer particle.

**Comment by Ephememory** [comment]
It looks like most of the weapon resources just don't have tracers assigned to them.
![image](https://user-images.githubusercontent.com/66768086/214686119-a7625deb-1bd3-40d7-8ff9-41ce6094960c.png)

**Comment by matekdev** [comment]
https://github.com/CigarLounge/sbox-TTT/pull/322

OK!!!
